import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

describe('local review width preference', () => {
  const values = new Map<string, string>()
  beforeEach(() => {
    vi.resetModules()
    values.clear()
    vi.stubGlobal('window', {})
    vi.stubGlobal('localStorage', { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => values.set(key, value), removeItem: (key: string) => values.delete(key) })
  })
  afterEach(() => vi.unstubAllGlobals())
  it('restores width and folder but excludes review drafts, threads and content from persistence', async () => {
    const { useUIStore: store } = await import('./uiStore')
    store.getState().setReviewListWidth(420)
    store.getState().setReviewConversation('session', 'thread')
    store.getState().setReviewFolder({ kind: 'topic', topicId: 'topic' })
    const data = JSON.parse(values.get('delive-review-view')!)
    expect(data.state).toEqual({ reviewFolder: { kind: 'topic', topicId: 'topic' }, reviewListWidth: 420, reviewFolderWidth: 176 })
    store.setState({ reviewListWidth: 380, reviewFolder: { kind: 'all' } })
    values.set('delive-review-view', JSON.stringify(data))
    await store.persist.rehydrate()
    expect(store.getState()).toMatchObject({ reviewListWidth: 420, reviewFolder: { kind: 'topic', topicId: 'topic' } })
  })
  it('defaults malformed, missing and out-of-range values without changing the saved folder', async () => {
    const { useUIStore: store, normalizeReviewListWidth } = await import('./uiStore')
    for (const value of [undefined, null, '420', -1, 279, Infinity, NaN, 2001]) expect(normalizeReviewListWidth(value)).toBe(380)
    expect(normalizeReviewListWidth(280)).toBe(280)
    values.set('delive-review-view', JSON.stringify({ state: { reviewFolder: { kind: 'unclassified' }, reviewListWidth: 'wrong' }, version: 0 }))
    await store.persist.rehydrate()
    expect(store.getState()).toMatchObject({ reviewListWidth: 380, reviewFolder: { kind: 'unclassified' } })
  })
  it('validates and restores the independent local folder width preference', async () => {
    const { useUIStore: store, normalizeReviewFolderWidth } = await import('./uiStore')
    for (const value of [undefined, null, '220', -1, 159, 261, Infinity, NaN]) expect(normalizeReviewFolderWidth(value)).toBe(176)
    expect(normalizeReviewFolderWidth(160)).toBe(160)
    expect(normalizeReviewFolderWidth(260)).toBe(260)
    store.getState().setReviewFolderWidth(220)
    store.getState().setReviewListWidth(420)
    const data = values.get('delive-review-view')!
    store.setState({ reviewFolderWidth: 176 })
    values.set('delive-review-view', data)
    await store.persist.rehydrate()
    expect(store.getState()).toMatchObject({ reviewFolderWidth: 220, reviewListWidth: 420 })
  })
  it('reconciles selection without forcing a mobile navigation transition', async () => {
    const { useUIStore: store } = await import('./uiStore')
    store.getState().setView('review')
    store.getState().setReviewSelection('newest')
    expect(store.getState()).toMatchObject({ reviewSessionId: 'newest', reviewDocumentOpen: false })
    store.getState().openReview('explicit')
    expect(store.getState()).toMatchObject({ reviewSessionId: 'explicit', reviewDocumentOpen: true })
    store.getState().setView('review')
    store.getState().setReviewSelection('filtered')
    expect(store.getState()).toMatchObject({ reviewSessionId: 'filtered', reviewDocumentOpen: false })
    expect(JSON.parse(values.get('delive-review-view')!).state).not.toHaveProperty('reviewDocumentOpen')
  })
})
