import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import fs from 'fs'
import path from 'path'
import os from 'os'
import { createHash } from 'crypto'
import type { BrowserWindow, IpcMain, IpcMainInvokeEvent } from 'electron'
const environment = vi.hoisted(() => ({ userData: '' }))
const nativeDialog = vi.hoisted(() => vi.fn())
vi.mock('electron', () => ({ app: { getPath: () => environment.userData }, dialog: { showMessageBox: nativeDialog } }))
vi.mock('../../electron/ipcSecurity', () => ({ assertMainWindowSender: vi.fn() }))

describe('original source preview identity and live context fences', () => {
  let root: string
  beforeEach(async () => { vi.resetModules(); root = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'kilo', 'delive-original-')); environment.userData = path.join(root, 'userdata') })
  afterEach(async () => { await fs.promises.rm(root, { recursive: true, force: true }) })
  async function setup() {
    const files = (await import('../../electron/fileStorage')).getFileStorageService()
    await files.getConfiguration()
    const originals = new (await import('../../electron/originalSources')).OriginalSourceService(environment.userData)
    const original = path.join(root, 'input.wav')
    await fs.promises.writeFile(original, 'ORIGINAL')
    originals.rememberSelection(original, 1)
    const source = await originals.register(original, 'record1', 1)
    const context = { sessionId: 'record1', title: 'Title', createdAt: 1000, titleRevision: 0 }
    await files.registerSessionContext(context)
    return { files, originals, original, source, context }
  }
  it('invalidates a preview after the same file is externally moved and reselected', async () => {
    const { originals, original, source, context } = await setup()
    const preview = await originals.preview(source.id, context, 1)
    const movedDirectory = path.join(root, 'moved')
    await fs.promises.mkdir(movedDirectory)
    const moved = path.join(movedDirectory, 'input.wav')
    await fs.promises.rename(original, moved)
    originals.rememberSelection(moved, 1)
    const registered = await originals.register(moved, context.sessionId, 1)
    expect(registered.revision).toBeGreaterThan(source.revision)
    await expect(originals.commit(preview.token, 1, async () => context)).rejects.toThrow(/path|revision/)
    expect(await fs.promises.readFile(moved, 'utf8')).toBe('ORIGINAL')
    expect(fs.existsSync(path.join(movedDirectory, preview.newName))).toBe(false)
  })
  it('rechecks title and deleted state when a previously approved request dispatches', async () => {
    const { files, originals, source, context, original } = await setup()
    const preview = await originals.preview(source.id, context, 1)
    await files.registerSessionContext({ ...context, title: 'Changed', titleRevision: 1 })
    await expect(originals.commit(preview.token, 1, () => files.getSessionContext(context.sessionId))).rejects.toThrow(/Title/)
    const next = await originals.preview(source.id, await files.getSessionContext(context.sessionId), 1)
    await files.recordDeletion(context.sessionId, 'commit')
    await expect(originals.commit(next.token, 1, () => files.getSessionContext(context.sessionId))).rejects.toThrow(/deleted/)
    expect(await fs.promises.readFile(original, 'utf8')).toBe('ORIGINAL')
  })
  it('rejects rename preview during a native source read lease and updates all shared references after release', async () => {
    const { originals, source, context } = await setup()
    const lease = await originals.acquireRead(source.id, context.sessionId)
    await expect(originals.preview(source.id, context, 1)).rejects.toThrow(/read|upload/)
    originals.releaseRead(lease.token)
    const preview = await originals.preview(source.id, context, 1)
    expect(preview.affectedSessionIds).toEqual([context.sessionId])
  })
  it('persists undo history and uses a fresh reverse preview without changing bytes or file identity', async () => {
    const { originals, original, source, context } = await setup()
    const before = await fs.promises.stat(original, { bigint: true })
    const checksum = createHash('sha256').update(await fs.promises.readFile(original)).digest('hex')
    const forward = await originals.preview(source.id, context, 1)
    const renamed = await originals.commit(forward.token, 1, async () => context)
    await expect(originals.commit(forward.token, 1, async () => context)).rejects.toThrow(/consumed/)
    const restarted = new (await import('../../electron/originalSources')).OriginalSourceService(environment.userData)
    const reverse = await restarted.preview(source.id, context, 1, true)
    expect(reverse.token).not.toBe(forward.token)
    expect(reverse.oldName).toBe(renamed.fileName)
    expect(reverse.newName).toBe('input.wav')
    expect(reverse.directory).toBe(root)
    const renamedPath = path.join(root, renamed.fileName)
    expect(fs.existsSync(original)).toBe(false)
    expect(createHash('sha256').update(await fs.promises.readFile(renamedPath)).digest('hex')).toBe(checksum)
    const restored = await restarted.commit(reverse.token, 1, async () => context)
    expect(restored.revision).toBe(renamed.revision + 1)
    const after = await fs.promises.stat(original, { bigint: true })
    expect([after.dev, after.ino, after.size]).toEqual([before.dev, before.ino, before.size])
    expect(createHash('sha256').update(await fs.promises.readFile(original)).digest('hex')).toBe(checksum)
    await expect(restarted.commit(reverse.token, 1, async () => context)).rejects.toThrow(/consumed/)
  }, 30000)
  it('rejects expired and busy reverse previews without changing the current original', async () => {
    const { originals, original, source, context } = await setup()
    const forward = await originals.preview(source.id, context, 1)
    const renamed = await originals.commit(forward.token, 1, async () => context)
    const reverse = await originals.preview(source.id, context, 1, true)
    const now = vi.spyOn(Date, 'now').mockReturnValue(reverse.expiresAt + 1)
    await expect(originals.commit(reverse.token, 1, async () => context)).rejects.toThrow(/preview/)
    now.mockRestore()
    const next = await originals.preview(source.id, context, 1, true)
    const lease = await originals.acquireRead(source.id, context.sessionId)
    await expect(originals.preview(source.id, context, 1, true)).rejects.toThrow(/read|upload/)
    await expect(originals.commit(next.token, 1, async () => context)).rejects.toThrow(/read|upload/)
    originals.releaseRead(lease.token)
    expect(fs.existsSync(original)).toBe(false)
    expect(await fs.promises.readFile(path.join(root, renamed.fileName), 'utf8')).toBe('ORIGINAL')
  }, 30000)
  it('native cancellation consumes the fresh undo token and displays exact paths, references and external-link warning', async () => {
    const { originals, original, source, context } = await setup()
    originals.rememberSelection(original, 1)
    await originals.register(original, 'record2', 1)
    const forward = await originals.preview(source.id, context, 1)
    const renamed = await originals.commit(forward.token, 1, async () => context)
    vi.spyOn(await import('../../electron/originalSources'), 'getOriginalSourceService').mockReturnValue(originals)
    const handlers = new Map<string, Parameters<IpcMain['handle']>[1]>()
    const send = vi.fn()
    const { registerOriginalSourceIpc } = await import('../../electron/originalSourceIpc')
    registerOriginalSourceIpc({ ipcMain: { on: vi.fn(), handle: (name: string, handler: Parameters<IpcMain['handle']>[1]) => handlers.set(name, handler) } as unknown as IpcMain, getMainWindow: () => ({ webContents: { send } }) as unknown as BrowserWindow })
    const event = { sender: { id: 1 } } as IpcMainInvokeEvent
    const result = await handlers.get('preview-original-undo')!(event, source.id, context.sessionId)
    expect(result.preview.token).not.toBe(forward.token)
    nativeDialog.mockResolvedValueOnce({ response: 0 })
    expect(await handlers.get('commit-original-rename')!(event, result.preview.token)).toBeNull()
    const dialogOptions = nativeDialog.mock.calls[nativeDialog.mock.calls.length - 1][1]
    expect(dialogOptions.message).toContain(renamed.fileName)
    expect(dialogOptions.message).toContain('input.wav')
    expect(dialogOptions.detail).toContain(root)
    expect(dialogOptions.detail).toContain('record1, record2')
    expect(dialogOptions.detail).toContain('External references and links cannot be repaired automatically')
    expect(() => originals.peek(result.preview.token, 1)).toThrow(/expired/)
    expect(send).not.toHaveBeenCalled()
    expect(fs.existsSync(original)).toBe(false)
    expect(await fs.promises.readFile(path.join(root, renamed.fileName), 'utf8')).toBe('ORIGINAL')
    const fresh = await handlers.get('preview-original-undo')!(event, source.id, context.sessionId)
    expect(fresh.preview.token).not.toBe(result.preview.token)
    nativeDialog.mockResolvedValueOnce({ response: 1 })
    const committed = await handlers.get('commit-original-rename')!(event, fresh.preview.token)
    expect(committed.ok).toBe(true)
    expect(committed.source.fileName).toBe('input.wav')
    expect(send).toHaveBeenCalledWith('original-source-changed', committed.source)
    expect(await fs.promises.readFile(original, 'utf8')).toBe('ORIGINAL')
  }, 30000)
})
