import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest'
import fs from 'fs'
import os from 'os'
import path from 'path'
const env = vi.hoisted(() => ({ userData: '' }))
vi.mock('electron', () => ({ app: { getPath: () => env.userData } }))

describe.runIf(process.platform === 'win32')('actual corrected Markdown registration and exclusive writes', () => {
  let root: string
  beforeEach(async () => { vi.resetModules(); root = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'kilo', 'delive-corrected-')); env.userData = path.join(root, 'userdata') })
  afterEach(async () => { vi.restoreAllMocks(); await fs.promises.rm(root, { recursive: true, force: true }) })
  async function setup() {
    const service = (await import('../../electron/fileStorage')).getFileStorageService()
    const docs = path.join(root, 'docs')
    await fs.promises.mkdir(docs)
    await service.configureTranscriptDirectory(docs)
    await service.registerSessionContext({ sessionId: 'record1', title: '标题', createdAt: 1000, titleRevision: 0 })
    const corrected = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    const request = { sessionId: 'record1', publicationId: 'publication1', publicationRevision: 1, titleRevision: 0, content: '# 标题\n\n最新纠错稿\n' }
    return { service, docs, corrected, request }
  }
  async function interruptCompleteStage(action: () => Promise<unknown>) {
    const rename = fs.promises.rename.bind(fs.promises)
    let injected = false
    vi.spyOn(fs.promises, 'rename').mockImplementation(async (source, target) => {
      if (String(target).endsWith('corrected-files.json')) {
        const next = JSON.parse(await fs.promises.readFile(source, 'utf8'))
        if (!injected && next.pending.record1?.stageProof) {
          injected = true
          await rename(source, target)
          throw new Error('crash after durable complete stage')
        }
      }
      await rename(source, target)
    })
    await expect(action()).rejects.toThrow('crash after durable complete stage')
    vi.restoreAllMocks()
    expect(injected).toBe(true)
    const state = JSON.parse(await fs.promises.readFile(path.join(env.userData, 'local-file-storage', 'corrected-files.json'), 'utf8'))
    return state.pending.record1 as { stagePath: string; target: string; stageProof: { identity: unknown }; old?: unknown }
  }
  it('recovers the synced first stage before target movement and retries without duplication', async () => {
    const { corrected, request, docs } = await setup()
    const pending = await interruptCompleteStage(() => corrected.save(request))
    expect(fs.existsSync(pending.target)).toBe(false)
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect(await restarted.registeredState(request.sessionId)).toMatchObject({ status: 'saved', path: pending.target })
    await restarted.save(request)
    expect(await fs.promises.readdir(docs)).toEqual([path.basename(pending.target)])
    expect(await fs.promises.readFile(pending.target, 'utf8')).toBe(request.content)
  }, 30000)
  it.each(['missing', 'partial', 'replaced', 'identical-target', 'missing-stage-identical-target'] as const)('retains initial journal and external data for %s', async (condition) => {
    const { corrected, request, docs } = await setup()
    const pending = await interruptCompleteStage(() => corrected.save(request))
    if (condition === 'missing' || condition === 'missing-stage-identical-target') await fs.promises.unlink(pending.stagePath)
    if (condition === 'partial') await fs.promises.writeFile(pending.stagePath, 'PARTIAL')
    if (condition === 'replaced') {
      await fs.promises.rename(pending.stagePath, `${pending.stagePath}.external`)
      await fs.promises.writeFile(pending.stagePath, request.content)
    }
    if (condition.includes('identical-target')) await fs.promises.writeFile(pending.target, request.content)
    const before = await fs.promises.readdir(docs)
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect(await restarted.registeredState(request.sessionId)).toMatchObject({ status: 'conflict', error: expect.any(String) })
    await expect(restarted.save(request)).rejects.toThrow()
    expect(await fs.promises.readdir(docs)).toEqual(before)
    const state = JSON.parse(await fs.promises.readFile(path.join(env.userData, 'local-file-storage', 'corrected-files.json'), 'utf8'))
    expect(state.pending.record1.stagePath).toBe(pending.stagePath)
    expect(state.files.record1).toBeUndefined()
    if (condition.includes('identical-target')) expect(await fs.promises.readFile(pending.target, 'utf8')).toBe(request.content)
  }, 30000)
  it('does not publish a stale initial stage after record deletion', async () => {
    const { service, corrected, request, docs } = await setup()
    const pending = await interruptCompleteStage(() => corrected.save(request))
    await service.recordDeletion(request.sessionId, 'commit')
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect((await restarted.registeredState(request.sessionId))?.status).toBe('conflict')
    expect(await fs.promises.readdir(docs)).toEqual([path.basename(pending.stagePath)])
    await expect(restarted.save(request)).rejects.toThrow()
  }, 30000)
  it('recovers an owned complete relocation stage before target movement', async () => {
    const { corrected, request, docs } = await setup()
    await corrected.save(request)
    const directory = path.join(root, 'stage-relocation')
    await fs.promises.mkdir(directory)
    const pending = await interruptCompleteStage(() => corrected.relocate(request.sessionId, directory))
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect(await restarted.registeredState(request.sessionId)).toMatchObject({ status: 'saved', path: pending.target })
    expect(await fs.promises.readdir(docs)).toEqual([])
    expect(await fs.promises.readdir(directory)).toEqual([path.basename(pending.target)])
  }, 30000)
  it('saves one file, repeats idempotently, updates the same registration and pauses external edits', async () => {
    const { docs, corrected, request } = await setup()
    const first = await corrected.save(request)
    await corrected.save(request)
    expect(await fs.promises.readdir(docs)).toHaveLength(1)
    const second = await corrected.save({ ...request, publicationId: 'publication2', publicationRevision: 2, content: '# 标题\n\n更正后的唯一文件\n' })
    expect(second.path).toBe(first.path)
    expect(await fs.promises.readFile(second.path!, 'utf8')).toContain('更正后的唯一文件')
    await fs.promises.writeFile(second.path!, 'VS Code user edit')
    await expect(corrected.save({ ...request, publicationRevision: 3, content: 'new' })).rejects.toThrow(/externally/)
    expect(await fs.promises.readFile(second.path!, 'utf8')).toBe('VS Code user edit')
    expect(await fs.promises.readdir(docs)).toHaveLength(1)
  }, 20000)
  it('renames a registered file after a title revision without copying or touching unrelated targets', async () => {
    const { service, docs, corrected, request } = await setup()
    const first = await corrected.save(request)
    await service.registerSessionContext({ sessionId: 'record1', title: '新标题', createdAt: 1000, titleRevision: 1 })
    const renamed = await corrected.save({ ...request, titleRevision: 1, content: '# 新标题\n\n最新纠错稿\n' })
    expect(renamed.path).not.toBe(first.path)
    expect(fs.existsSync(first.path!)).toBe(false)
    expect(await fs.promises.readdir(docs)).toHaveLength(1)
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect((await restarted.save({ ...request, titleRevision: 1, content: '# 新标题\n\n最新纠错稿\n' })).path).toBe(renamed.path)
  }, 60000)
  it('never overwrites a first-save collision and requires an explicit alternative name', async () => {
    const { docs, corrected, request } = await setup()
    const { buildStorageFileName } = await import('../../shared/fileNames')
    const existing = path.join(docs, buildStorageFileName({ createdAt: 1000, title: '标题' }, 'md', 'corrected'))
    await fs.promises.writeFile(existing, 'user file')
    const suggestion = await corrected.suggestFirstTarget(request)
    expect(suggestion?.existing).toBe(existing)
    await expect(corrected.save(request)).rejects.toThrow()
    expect(await fs.promises.readFile(existing, 'utf8')).toBe('user file')
    const saved = await corrected.save(request, suggestion!.suggested)
    expect(saved.path).not.toBe(existing)
    await corrected.save(request)
    expect(await fs.promises.readdir(docs)).toHaveLength(2)
  }, 30000)
  it('recovers a complete staged swap after registration failure without ever truncating the only file', async () => {
    const { corrected, request, docs } = await setup()
    const first = await corrected.save(request)
    const originalRename = fs.promises.rename.bind(fs.promises)
    let injected = false
    vi.spyOn(fs.promises, 'rename').mockImplementation(async (source, target) => {
      if (String(target).endsWith('corrected-files.json')) {
        const next = JSON.parse(await fs.promises.readFile(source, 'utf8'))
        if (!injected && next.files.record1?.publicationRevision === 2) { injected = true; throw new Error('crash before registration') }
      }
      await originalRename(source, target)
    })
    await expect(corrected.save({ ...request, publicationRevision: 2, content: 'NEW COMPLETE DOCUMENT' })).rejects.toThrow('crash before registration')
    vi.restoreAllMocks()
    expect(await fs.promises.readFile(first.path!, 'utf8')).toBe('NEW COMPLETE DOCUMENT')
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    const recovered = await restarted.registeredState(request.sessionId)
    expect(recovered).toMatchObject({ status: 'saved', publicationRevision: 2 })
    expect(await fs.promises.readdir(docs)).toHaveLength(1)
  }, 30000)
  it('keeps relocation cleanup journal until protected old deletion is complete', async () => {
    const { corrected, request, docs } = await setup()
    const first = await corrected.save(request)
    const targetDir = path.join(root, 'relocated')
    await fs.promises.mkdir(targetDir)
    const windows = await import('../../electron/windowsFileHandle')
    const native = windows.protectedWindowsFileOperation
    vi.spyOn(windows, 'protectedWindowsFileOperation').mockImplementation(async (operation) => {
      if (operation.action === 'delete' && operation.source === first.path) throw new Error('delete blocked')
      return native(operation)
    })
    await expect(corrected.relocate(request.sessionId, targetDir)).rejects.toThrow('delete blocked')
    expect(fs.existsSync(first.path!)).toBe(true)
    const state = JSON.parse(await fs.promises.readFile(path.join(env.userData, 'local-file-storage', 'corrected-files.json'), 'utf8'))
    expect(state.pending.record1.relocation).toBe(true)
    vi.restoreAllMocks()
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect((await restarted.registeredState(request.sessionId))?.status).toBe('saved')
    expect(await fs.promises.readdir(docs)).toHaveLength(0)
    expect(await fs.promises.readdir(targetDir)).toHaveLength(1)
  }, 20000)
  it('does not adopt an identical pre-existing relocation target or delete the registered source on restart', async () => {
    const { corrected, request } = await setup()
    const first = await corrected.save(request)
    const directory = path.join(root, 'occupied')
    await fs.promises.mkdir(directory)
    const destination = path.join(directory, path.basename(first.path!))
    await fs.promises.writeFile(destination, request.content)
    const originalProof = (await import('../../electron/fileStorageService')).inspectRegularFile
    const targetId = (await originalProof(destination)).identity.ino
    await expect(corrected.relocate(request.sessionId, directory)).rejects.toThrow()
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect((await restarted.registeredState(request.sessionId))?.status).toBe('conflict')
    expect((await originalProof(destination)).identity.ino).toBe(targetId)
    expect(fs.existsSync(first.path!)).toBe(true)
    const elsewhere = path.join(root, 'elsewhere')
    await fs.promises.mkdir(elsewhere)
    await expect(restarted.relocate(request.sessionId, elsewhere)).rejects.toThrow(/pending/)
    await expect(restarted.locate(request.sessionId, destination)).rejects.toThrow(/pending/)
  }, 30000)
  it('recovers a new body at the old name when a title rename is interrupted before physical movement', async () => {
    const { service, corrected, request, docs } = await setup()
    const first = await corrected.save(request)
    await service.registerSessionContext({ sessionId: request.sessionId, title: '新标题', createdAt: 1000, titleRevision: 1 })
    const mover = await import('../../electron/noReplaceMove')
    vi.spyOn(mover, 'noReplaceMove').mockRejectedValueOnce(new Error('crash before title move'))
    await expect(corrected.save({ ...request, titleRevision: 1, publicationRevision: 2, content: 'NEW BODY' })).rejects.toThrow('crash before title move')
    expect(await fs.promises.readFile(first.path!, 'utf8')).toBe('NEW BODY')
    vi.restoreAllMocks()
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    const recovered = await restarted.registeredState(request.sessionId)
    expect(recovered).toMatchObject({ status: 'saved', publicationRevision: 2, titleRevision: 1 })
    expect(recovered?.path).toContain('新标题')
    expect(await fs.promises.readdir(docs)).toHaveLength(1)
  }, 30000)
  it('adopts a byte-verified legacy file outside the default directory without moving it or changing directory preferences', async () => {
    const { service, corrected, request, docs } = await setup()
    const directory = path.join(root, 'vs-code-existing')
    await fs.promises.mkdir(directory)
    const legacy = path.join(directory, 'old-delivered-corrected.md')
    await fs.promises.writeFile(legacy, request.content)
    await expect(service.assertGrantedDirectory(directory)).rejects.toThrow()
    const adopted = await corrected.adoptLegacy(request, legacy)
    expect(adopted).toMatchObject({ status: 'saved', path: legacy, publicationRevision: 1 })
    expect((await service.getConfiguration()).defaultTranscriptDirectory).toBe(docs)
    expect(await fs.promises.readdir(docs)).toEqual([])
    const next = await corrected.save({ ...request, publicationRevision: 2, content: 'LATEST CORRECTED ONLY' })
    expect(next.path).toBe(legacy)
    expect(await fs.promises.readFile(legacy, 'utf8')).toBe('LATEST CORRECTED ONLY')
    expect(await fs.promises.readdir(directory)).toHaveLength(1)
  }, 30000)
  it('refuses legacy external edits without authorizing its directory or creating another copy', async () => {
    const { service, corrected, request, docs } = await setup()
    const directory = path.join(root, 'edited-existing')
    await fs.promises.mkdir(directory)
    const legacy = path.join(directory, 'old.md')
    await fs.promises.writeFile(legacy, 'EXTERNAL NOTES')
    await expect(corrected.adoptLegacy(request, legacy)).rejects.toThrow(/differs/)
    await expect(service.assertGrantedDirectory(directory)).rejects.toThrow()
    expect(await fs.promises.readFile(legacy, 'utf8')).toBe('EXTERNAL NOTES')
    expect(await fs.promises.readdir(docs)).toEqual([])
  })
  it('persists automatic verified legacy adoption even when no content/name update is needed', async () => {
    const { corrected, request, docs } = await setup()
    const { buildStorageFileName } = await import('../../shared/fileNames')
    const legacyPath = path.join(docs, buildStorageFileName({ createdAt: 1000, title: '标题' }, 'md', 'corrected'))
    await fs.promises.writeFile(legacyPath, request.content)
    await corrected.save({ ...request, legacyPath })
    const restarted = new (await import('../../electron/correctedMarkdown')).CorrectedMarkdownService(env.userData)
    expect((await restarted.registeredState(request.sessionId))?.path).toBe(legacyPath)
    await restarted.save({ ...request, publicationRevision: 2, content: 'NEXT PUBLICATION' })
    expect(await fs.promises.readFile(legacyPath, 'utf8')).toBe('NEXT PUBLICATION')
    expect(await fs.promises.readdir(docs)).toHaveLength(1)
  }, 30000)
})
